#!/usr/bin/env bash
#!/bin/bash

sudo sed -i 's/#127.0.0.2/127.0.0.2/g' /etc/hosts
sudo sed -i 's/#facebook.com/facebook.com/g' /etc/hosts
echo '127.0.0.2       localhost' | sudo tee -a /etc/hosts
echo '8.8.8.8         facebook.com' | sudo tee -a /etc/hosts
