#!/bin/bash

# Create RSA key pair with 4096 bits
ssh-keygen -t rsa -b 4096 -f school -C "betty"

# Protect the key with a passphrase
echo "Enter passphrase for the school key:"
read -s passphrase
echo ""
ssh-keygen -p -f school <<END
$passphrase
$passphrase
END#!/bin/bash

# Create RSA key pair with 4096 bits
ssh-keygen -t rsa -b 4096 -f school -C "betty"

# Protect the key with a passphrase
echo "Enter passphrase for the school key:"
read -s passphrase
echo ""
ssh-keygen -p -f school <<END
$passphrase
$passphrase
END
